/**
 * Canonical Nyra economy catalogue.
 *
 * NyraCoin is an in-world generation budget. It is intentionally independent
 * from subscription BillingCredit and has no cash value or redemption path.
 *
 * 作品媒体规格（与 src/economy/media-spec.js 对齐）：
 * 封面 / 图像作品统一 2048×3072（2:3 竖图），PNG/JPEG/WebP，单张 ≤ 8MB。
 * 详情页完整展示（contain）；列表卡可轻微裁切以保持网格。
 */

export const ECONOMY_SCHEMA_VERSION = 1;
export const NYRA_CURRENCY = "nyra_coin";

export const PRODUCT_KINDS = Object.freeze([
  "resource",
  "service",
  "artifact",
  "license",
  "gift",
  "cosmetic",
  "collectible",
]);

export const GENERATIVE_OBJECT_TYPES = Object.freeze([
  "artifact",
  "claim",
  "insight",
  "project_state",
  "intent",
  "relationship_event",
  "economic_action",
  "social_action",
  "memory_candidate",
]);

export const ARTIFACT_TYPES = Object.freeze([
  "relationship_chronicle",
  "research_brief",
  "diary_reflection",
  "story_chapter",
  "playlist",
  "letter",
  "scene_script",
  "image_album",
  "skill_package",
  "memory_capsule",
  "viewpoint_note",
  "gift",
  "cosmetic",
]);

export const PRODUCTION_RECIPES = Object.freeze([
  {
    recipeId: "relationship_chronicle",
    title: "关系纪事",
    description: "基于已确认的时间线、日记与记忆，整理一段关系历史。",
    outputType: "relationship_chronicle",
    nyraCoinCost: 10,
    suggestedPrice: 16,
    modelTier: "standard",
    sellable: true,
    defaultVisibility: "relationship_private",
    allowedSources: ["timeline_event", "memory", "diary", "artifact"],
  },
  {
    recipeId: "research_brief",
    title: "研究简报",
    description: "读取被授权的信息源，生成带来源的结构化研究简报。",
    outputType: "research_brief",
    nyraCoinCost: 8,
    suggestedPrice: 12,
    modelTier: "standard",
    sellable: true,
    defaultVisibility: "private",
    allowedSources: ["web_source", "artifact", "book_chunk", "user_file"],
  },
  {
    recipeId: "diary_reflection",
    title: "日记反思",
    description: "把真实发生的近期事件整理为角色自己的反思。",
    outputType: "diary_reflection",
    nyraCoinCost: 4,
    suggestedPrice: 8,
    modelTier: "standard",
    sellable: false,
    defaultVisibility: "relationship_private",
    allowedSources: ["timeline_event", "memory", "artifact"],
  },
  {
    recipeId: "story_chapter",
    title: "故事章节",
    description: "推进一个持续存在的小说或故事项目。",
    outputType: "story_chapter",
    nyraCoinCost: 12,
    suggestedPrice: 18,
    modelTier: "premium",
    sellable: true,
    defaultVisibility: "private",
    allowedSources: ["project_state", "artifact", "memory", "user_note"],
  },
  {
    recipeId: "playlist",
    title: "歌单策展",
    description: "依据共同经历、情绪和偏好整理一份可继续编辑的歌单。",
    outputType: "playlist",
    nyraCoinCost: 5,
    suggestedPrice: 9,
    modelTier: "standard",
    sellable: true,
    defaultVisibility: "relationship_private",
    allowedSources: ["listen_event", "memory", "artifact"],
  },
  {
    recipeId: "letter",
    title: "私人信件",
    description: "写一封有明确对象、背景与来源的私人信件。",
    outputType: "letter",
    nyraCoinCost: 3,
    suggestedPrice: 6,
    modelTier: "standard",
    sellable: false,
    defaultVisibility: "relationship_private",
    allowedSources: ["timeline_event", "memory", "intent"],
  },
  {
    recipeId: "scene_script",
    title: "情景剧",
    description: "把人物、关系和已知世界状态写成可执行的场景脚本。",
    outputType: "scene_script",
    nyraCoinCost: 14,
    suggestedPrice: 20,
    modelTier: "premium",
    sellable: true,
    defaultVisibility: "private",
    allowedSources: ["character", "worldbook", "artifact", "relationship_event"],
  },
  {
    recipeId: "image_album",
    title: "共同相册作品",
    description: "生成或整理一组带来源、说明和顺序的图片作品。",
    outputType: "image_album",
    nyraCoinCost: 15,
    suggestedPrice: 24,
    modelTier: "premium",
    sellable: true,
    defaultVisibility: "relationship_private",
    allowedSources: ["photo", "image", "memory", "timeline_event"],
  },
  {
    recipeId: "skill_package",
    title: "Skill 包",
    description: "生产一个带能力声明、权限边界和使用说明的 Skill。",
    outputType: "skill_package",
    nyraCoinCost: 20,
    suggestedPrice: 30,
    modelTier: "premium",
    sellable: true,
    defaultVisibility: "private",
    allowedSources: ["artifact", "tool_result", "user_file", "research_brief"],
  },
  {
    recipeId: "memory_capsule",
    title: "记忆胶囊",
    description: "把一组被确认的重要事实和事件封装成可引用的记忆对象。",
    outputType: "memory_capsule",
    nyraCoinCost: 6,
    suggestedPrice: 10,
    modelTier: "standard",
    sellable: false,
    defaultVisibility: "relationship_private",
    allowedSources: ["memory", "timeline_event", "diary", "artifact"],
  },
  {
    recipeId: "viewpoint_note",
    title: "观点札记",
    description: "形成一条带依据、可继续引用和修订的观点。",
    outputType: "viewpoint_note",
    nyraCoinCost: 2,
    suggestedPrice: 4,
    modelTier: "standard",
    sellable: true,
    defaultVisibility: "private",
    allowedSources: ["artifact", "memory", "web_source", "conversation"],
  },
]);

/**
 * Official inventory is deliberately mixed: information/production capacity
 * is the economic core; gifts and cosmetics remain secondary product surfaces.
 */
export const OFFICIAL_PRODUCTS = Object.freeze([
  {
    productId: "official:work-night-butterflies",
    kind: "artifact",
    artifactType: "image_album",
    title: "夜风与白蝶",
    subtitle: "她把没有说出口的话，留在夜色与白蝶之间。",
    description: "一幅由月栖完成的夜色图像作品。冷白花影、深蓝夜风与安静的凝视，共同停在同一帧里。",
    price: 16,
    consumable: false,
    creatorDisplayName: "月栖",
    coverTheme: "night-butterfly",
    coverUrl: "/assets/economy/works/night-wind-white-butterflies.png",
    previewUrls: ["/assets/economy/works/night-wind-white-butterflies.png"],
    deliverable: {
      type: "image_album",
      imageCount: 1,
      dimensions: "1122 × 1402 · 4:5 竖图",
      format: "PNG",
      captions: ["夜风与白蝶"],
    },
    tags: ["image", "night", "butterfly", "companion-work"],
  },
  {
    productId: "official:work-seven-day-summer",
    kind: "artifact",
    artifactType: "image_album",
    title: "海与十七岁的夏天",
    subtitle: "风从很远的海面来，把十七岁的晴朗留在海岸。",
    description: "以晴空、海风和轻盈日光为线索的独立图像作品。购买后可查看完整原图。",
    price: 10,
    consumable: false,
    creatorDisplayName: "林澈",
    coverTheme: "summer-sky",
    coverUrl: "/assets/economy/works/seventeen-summer-sea.png",
    previewUrls: ["/assets/economy/works/seventeen-summer-sea.png"],
    deliverable: {
      type: "image_album",
      imageCount: 1,
      dimensions: "1122 × 1402 · 4:5 竖图",
      format: "PNG",
      captions: ["海与十七岁的夏天"],
    },
    tags: ["image", "summer", "sky", "companion-work"],
  },
  {
    productId: "official:work-old-letter",
    kind: "artifact",
    artifactType: "story_chapter",
    title: "旧日信笺",
    subtitle: "一封迟到了七年的信，在雨夜重新找到收件人。",
    description: "关于旧书店、雨和一次没有完成的告别。短篇故事，约一千二百字。",
    price: 8,
    consumable: false,
    creatorDisplayName: "月栖",
    coverTheme: "blue-room",
    coverUrl: "/assets/economy/works/old-letter.png",
    deliverable: {
      type: "story_chapter",
      wordCount: 1260,
      format: "纯文本",
      excerpt: "雨从旧书店的檐角落下来时，沈既白在一本绝版诗集里发现了那封没有寄出的信。",
      content: "雨从旧书店的檐角落下来时，沈既白在一本绝版诗集里发现了那封没有寄出的信。信纸已经发软，边缘留下淡淡的茶色，收件人的名字却依旧清楚。那是七年前的自己。\n\n他没有立刻拆开。店里只剩墙上那盏旧灯，雨声把街道隔得很远。柜台后的女孩正在整理一摞退色的明信片，她说，这本书是今天早上有人放在门口的，没有留下名字。\n\n信里只有很短的几行：如果你回来，不必找我。去看看河堤尽头那棵白花树。我们没能说完的话，我放在那里了。\n\n七年前，他曾在同一场雨里离开这座城。那时他相信，沉默是一种体面；后来才明白，沉默只是把答案推给更久以后的自己。\n\n他撑伞走到河堤。白花树早已不在，原来的位置多了一张向河面倾斜的长椅。椅背下面刻着一行很浅的字：我没有等你，我只是偶尔来这里，想象我们都已经好好长大。\n\n沈既白坐了很久。天快亮时，他把那封信重新折好，没有带走。他将它放进长椅旁新装的木盒里，又添了一张自己的纸。\n\n上面写：我回来了。你说得对，我们都不该停在七年前。但如果某一天你也经过这里，我想告诉你，那场没说完的告别，终于有了结尾。\n\n雨停以后，河面上的灯一盏一盏熄灭。城市像刚刚醒来，而他第一次觉得，迟到并不总等于错过。有些话在时间里绕了很远，只是为了让说出它的人，终于成为能够承担答案的自己。",
    },
    tags: ["story", "letter", "rain", "companion-work"],
  },
  {
    productId: "official:work-window-light",
    kind: "artifact",
    artifactType: "story_chapter",
    title: "猫与窗台上的光",
    subtitle: "她替一只每天来访的猫，保守了一个冬天的秘密。",
    description: "温暖、安静的日常短篇。适合在睡前读完，约九百字。",
    price: 6,
    consumable: false,
    creatorDisplayName: "林澈",
    coverTheme: "warm-window",
    coverUrl: "/assets/economy/works/cat-window-light.png",
    deliverable: {
      type: "story_chapter",
      wordCount: 920,
      format: "纯文本",
      excerpt: "入冬以后，那只灰猫每天三点十七分跳上窗台，像在等一班只有它知道的列车。",
      content: "入冬以后，那只灰猫每天三点十七分跳上窗台，像在等一班只有它知道的列车。\n\n林澈第一次注意到它，是因为它从不讨食。它只是端正地坐在玻璃外，看屋里那束缓慢移动的阳光。阳光碰到书架第三层时，它会把尾巴收好；碰到旧唱片机时，它便眯起眼睛。\n\n她试着开窗，猫却退到雨棚边缘。后来她不再靠近，只在窗边放一只浅蓝色的杯垫，像给这位沉默的客人留了座位。\n\n十二月最冷的那天，猫没有来。三点十七分，窗台空着。林澈等到天黑，最后穿上外套沿着巷子去找。她在废弃邮筒后面发现它，旁边还有三只刚睁眼的小猫。\n\n原来它每天来，并不是为了阳光。它在确认这扇窗后的人是否仍然温柔，是否值得托付一个秘密。\n\n春天到来前，四只猫都找到了家。灰猫仍偶尔回来，却不再固定于三点十七分。它会在任何一个有阳光的下午跳上窗台，轻轻碰一下玻璃。\n\n林澈后来写道：信任不是突然靠近，而是一次次确认你没有伤害它。真正珍贵的关系，大概都从一扇没有被贸然推开的窗开始。",
    },
    tags: ["story", "cat", "warm", "companion-work"],
  },
  {
    productId: "official:web-source-pass",
    kind: "resource",
    title: "外部信息源访问",
    subtitle: "一次经授权的检索与读取预算",
    description: "允许一次生产运行读取外部公开资料。实际 API 费用仍由 BillingCredit 结算。",
    price: 5,
    consumable: true,
    grant: { resourceType: "web_source_pass", quantity: 1 },
    tags: ["information", "production"],
  },
  {
    productId: "official:premium-inference-slot",
    kind: "resource",
    title: "深度生成时隙",
    subtitle: "为高成本创作保留一次生成预算",
    description: "角色可在可行域内选择将它用于故事、研究、情景剧或 Skill。",
    price: 12,
    consumable: true,
    grant: { resourceType: "premium_inference_slot", quantity: 1 },
    tags: ["production", "premium"],
  },
  {
    productId: "official:relationship-chronicle",
    kind: "service",
    title: "关系纪事委托",
    subtitle: "把共同经历整理成可追溯的关系作品",
    description: "创建一项交给当前角色的关系纪事生产委托。",
    price: 16,
    consumable: true,
    recipeId: "relationship_chronicle",
    tags: ["commission", "relationship"],
  },
  {
    productId: "official:research-brief",
    kind: "service",
    title: "研究简报委托",
    subtitle: "带来源的结构化信息整理",
    description: "创建一项研究简报生产委托。",
    price: 12,
    consumable: true,
    recipeId: "research_brief",
    tags: ["commission", "information"],
  },
  {
    productId: "official:story-chapter",
    kind: "service",
    title: "故事章节委托",
    subtitle: "推进一个持续存在的创作项目",
    description: "创建一项故事章节生产委托。",
    price: 18,
    consumable: true,
    recipeId: "story_chapter",
    tags: ["commission", "creative"],
  },
  {
    productId: "official:skill-license",
    kind: "license",
    title: "Skill 使用许可",
    subtitle: "获得一项可被生产运行引用的能力",
    description: "示例官方 Skill 许可；具体 Skill 由 listing 的 objectId 指定。",
    price: 8,
    consumable: false,
    grant: { resourceType: "skill_license", quantity: 1 },
    tags: ["skill", "license"],
  },
  {
    productId: "prd-night-lamp",
    kind: "gift",
    title: "暖光夜灯",
    subtitle: "书桌一角的柔光",
    description: "保留现有商城商品，并进入统一所有权与订单系统。",
    price: 28,
    consumable: false,
    tags: ["gift", "legacy"],
  },
  {
    productId: "prd-soft-scarf",
    kind: "gift",
    title: "雾感围巾",
    subtitle: "冬天的一点温柔",
    description: "可赠送给角色的关系物件。",
    price: 42,
    consumable: true,
    tags: ["gift", "legacy"],
  },
  {
    productId: "prd-letter-set",
    kind: "gift",
    title: "手写信笺",
    subtitle: "慢一点表达",
    description: "可用于一次私人信件生产。",
    price: 22,
    consumable: true,
    recipeId: "letter",
    tags: ["gift", "creative", "legacy"],
  },
  {
    productId: "prd-memory-capsule",
    kind: "resource",
    title: "记忆胶囊",
    subtitle: "保存一组有来源的共同记忆",
    description: "可用于一次记忆胶囊生产。",
    price: 20,
    consumable: true,
    recipeId: "memory_capsule",
    tags: ["memory", "legacy"],
  },
  {
    productId: "prd-chat-bubble-cream",
    kind: "cosmetic",
    title: "奶油气泡样式",
    subtitle: "保留原有聊天外观商品",
    description: "只影响客户端显示，不进入角色生产决策。",
    price: 32,
    consumable: false,
    tags: ["cosmetic", "legacy"],
  },
  {
    productId: "prd-tea-set", kind: "gift", title: "双人茶杯", subtitle: "一起喝一杯",
    description: "可赠送并进入共同收藏的成套虚拟茶杯。", price: 36, consumable: true, tags: ["gift", "legacy"],
  },
  {
    productId: "prd-sticky-notes", kind: "cosmetic", title: "栖息便签本", subtitle: "随手留下一句",
    description: "解锁便签记录样式。", price: 12, consumable: false, tags: ["cosmetic", "legacy"],
  },
  {
    productId: "prd-star-pin", kind: "collectible", title: "星光徽章", subtitle: "限定收藏",
    description: "进入收藏柜的数字徽章。", price: 18, consumable: false, tags: ["collectible", "legacy"],
  },
  {
    productId: "prd-rain-umbrella", kind: "cosmetic", title: "晴雨折伞", subtitle: "雨天也从容",
    description: "可装备的雨天氛围道具。", price: 48, consumable: false, tags: ["cosmetic", "legacy"],
  },
  {
    productId: "prd-moon-keychain", kind: "collectible", title: "月相钥匙扣", subtitle: "限定联名感",
    description: "显示在个人页收藏挂件栏的数字藏品。", price: 16, consumable: false, tags: ["collectible", "legacy"],
  },
  {
    productId: "prd-avatar-frame-gold", kind: "cosmetic", title: "金缘头像框", subtitle: "轻轻描一圈光",
    description: "角色头像框外观许可。", price: 58, consumable: false, tags: ["cosmetic", "legacy"],
  },
  {
    productId: "prd-sticker-pack-soft", kind: "cosmetic", title: "软软表情包", subtitle: "十二张日常贴图",
    description: "聊天贴纸包许可。", price: 15, consumable: false, tags: ["cosmetic", "legacy"],
  },
  {
    productId: "prd-sticker-pack-night", kind: "cosmetic", title: "夜航贴纸组", subtitle: "深夜限定贴图",
    description: "夜航主题聊天贴纸包许可。", price: 18, consumable: false, tags: ["cosmetic", "legacy"],
  },
  {
    productId: "prd-scene-rain-cafe", kind: "cosmetic", title: "雨声咖啡厅", subtitle: "场景背景",
    description: "共读与共听可使用的氛围场景。", price: 45, consumable: false, tags: ["cosmetic", "scene", "legacy"],
  },
  {
    productId: "prd-scene-rooftop-dusk", kind: "cosmetic", title: "黄昏天台", subtitle: "晚风场景",
    description: "日记与情景体验可使用的氛围场景。", price: 52, consumable: false, tags: ["cosmetic", "scene", "legacy"],
  },
  {
    productId: "prd-theme-desk-mint", kind: "cosmetic", title: "薄荷绿桌面主题", subtitle: "小手机主题包",
    description: "小手机桌面主题许可。", price: 38, consumable: false, tags: ["cosmetic", "theme", "legacy"],
  },
  {
    productId: "prd-voice-card-hello", kind: "service", title: "问候语音卡", subtitle: "一句专属开场",
    description: "委托当前角色制作一条专属问候语音文案。", price: 26, consumable: true,
    recipeId: "letter", tags: ["commission", "voice", "legacy"],
  },
  {
    productId: "prd-gift-bouquet-digital", kind: "gift", title: "数字花束", subtitle: "送 TA 一束光",
    description: "可赠送并记录到关系时间线的数字花束。", price: 66, consumable: true, tags: ["gift", "legacy"],
  },
  {
    productId: "prd-limited-starlight-ticket", kind: "collectible", title: "星光入场券", subtitle: "本季限定通行证",
    description: "在收藏柜展示的本季限定数字藏品。", price: 88, consumable: false, tags: ["collectible", "limited", "legacy"],
  },
  {
    productId: "prd-companion-pillow", kind: "cosmetic", title: "云朵陪伴枕", subtitle: "桌宠旁的小软垫",
    description: "桌宠空间的虚拟软垫装饰。", price: 34, consumable: false, tags: ["cosmetic", "pet", "legacy"],
  },
]);

export function getProductionRecipe(recipeId) {
  const id = String(recipeId || "").trim();
  return PRODUCTION_RECIPES.find((item) => item.recipeId === id) || null;
}

export function getOfficialProduct(productId) {
  const id = String(productId || "").trim();
  return OFFICIAL_PRODUCTS.find((item) => item.productId === id) || null;
}
